name: Deploy GitBook to GitHub Pages

on:
  push:
    branches: [ source ]
  # 允许手动触发工作流
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source branch
      uses: actions/checkout@v4
      with:
        ref: source
        fetch-depth: 0

    - name: Setup Node.js 11
      uses: actions/setup-node@v4
      with:
        node-version: '11'

    - name: Install GitBook CLI
      run: npm install -g gitbook-cli@2.3.2

    - name: Install GitBook and plugins
      run: |
        gitbook install
        
    - name: Build GitBook
      run: gitbook build

    - name: Deploy to main branch
      run: |
        # 配置 git
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        
        # 切换到 main 分支
        git checkout --orphan main
        
        # 删除所有文件，只保留 _book 内容
        git rm -rf .
        
        # 复制 _book 内容到根目录
        cp -r _book/* .
        cp _book/.* . 2>/dev/null || true
        
        # 添加 .nojekyll 文件
        touch .nojekyll
        
        # 提交并推送
        git add .
        git commit -m "Deploy GitBook - $(date +'%Y-%m-%d %H:%M:%S')"
        git push origin main --force
